### PR TITLE
Fixes and minor rewording throughout

### PR DESCRIPTION
**Pull request by kmgallahan**
These edits are mostly minor fixes related to spelling, capitalization, and grammar, with a couple of spots of rewording to help with readability.

One file was deleted which appeared to be a redundant getting started doc that was no longer in use.

Some changes were made to the V2 docs with bulk replacements, but the V3 docs were the focus.

### CODE REVIEW

**Review by FrankBakkerNl — APPROVED** [review]
😃

**Review by phillipsawyer — APPROVED** [review]
This is so thorough ♥

**Comment by kmgallahan** [comment]
I looked at the deploy log and saw these messages:

> 7:23:52 PM: Exhaustive list of all broken links found:
> 7:23:52 PM: 
> 7:23:52 PM: - On source page path = /404.html:
> 7:23:52 PM:    -> linking to /docs/get_started_index

which looks like it might be related to the file I deleted (assuming _index isn't relevant...). I've added the file back.

@FrankBakkerNl thoughts?

**Comment by FrankBakkerNl** [comment]
I don't really know a lot about the structure of the docs, @helto4real maybe you know?

**Comment by helto4real** [comment]
I can check it out

**Comment by helto4real** [comment]
So I fixed the error. Since you renamed the id and that page is linked in the template it fails everywhere :)

**Pull request merged**
